irplanner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('planner/', include('planner.urls'))
]

planner/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('series/<int:series_id>/', views.series, name='series'),
    path('week/<int:week_id>/', views.week, name='week'),
]

planner/models.py
from datetime import datetime, time
from django.db import models


class Series(models.Model):
    series_name = models.CharField(max_length=200)
    start_time = models.TimeField()
    time_between_sessions = models.DurationField()

    def __str__(self):
        return self.series_name


class CarClass(models.Model):
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    class_name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.series.series_name} ({self.class_name})"


class Week(models.Model):
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    week_no = models.IntegerField()
    track = models.CharField

    def __str__(self):
        return f"{self.series.series_name} week {self.week_no}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        timeslots = list[time]()
        start_time = self.series.start_time
        timeslots.append(start_time)
        slot_datetime = datetime(2000, 1, 1, hour=start_time.hour, minute=start_time.minute)
        slot_datetime += self.series.time_between_sessions
        while slot_datetime < datetime(2000, 1, 2):
            timeslots.append(slot_datetime.time())
            slot_datetime += self.series.time_between_sessions
        Session.objects.filter(week=self).delete()
        for day in range(0, 7):
            for slot in timeslots:
                Session.objects.create(week=self, day=day, time=slot)


class Session(models.Model):
    week = models.ForeignKey(Week, on_delete=models.CASCADE)
    day = models.IntegerField()
    time = models.TimeField()

    def __str__(self):
        return f"{self.week.__str__()}: day {self.day} at {self.time}"

    def day_name(self):
        return {0: "Tuesday",
                1: "Wednesday",
                2: "Thursday",
                3: "Friday",
                4: "Saturday",
                5: "Sunday",
                6: "Monday"}[self.day]


class Racer(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    car_class = models.ForeignKey(CarClass, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}: {self.session.__str__()}"

planner/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.template import loader

from .models import Series, Session, Week


def index(request):
    series_list = Series.objects.order_by('series_name')
    template = loader.get_template('planner/index.html')
    context = {
        'series_list': series_list,
    }
    return render(request, 'planner/index.html', context)


def series(request, series_id):
    s = get_object_or_404(Series, pk=series_id)
    week_list = s.week_set.all()
    context = {
        'week_list': week_list
    }
    return render(request, 'planner/series.html', context)


def week(request, week_id):
    w = get_object_or_404(Week, pk=week_id)
    session_list = w.session_set.all().order_by('time')
    session_matrix = list[list[Session]]()
    for day in range(0, 7):
        session_matrix.append(list[Session]())
    for session in session_list:
        session_matrix[session.day].append(session)
    context = {
        'session_matrix': session_matrix
    }
    return render(request, 'planner/week.html', context)

planner/templates/planner/index.html
{% if series_list %}
    <ul>
        {% for series in series_list %}
            <li><a href="{% url 'series' series.id %}">{{ series.series_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No series yet available</p>
{% endif %}

planner/templates/planner/series.html
{% if week_list %}
    <ul>
        {% for week in week_list %}
            <li><a href="{% url 'week' week.id %}"/>Week {{ week.week_no }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>no weeks currently available</p>
{% endif %}

planner/templates/planner/week.html
{% if session_matrix %}
All times in GMT
<ul>
    <table border="1">
    {% for timeslot in session_matrix %}
        <tr>
        {% for session in timeslot %}
            <td><b>{{ session.day_name }}, {{ session.time }}</b>
                {% for racer in session.racer_set.all %}
                    <p>{{ racer.name }}</p>
                {% endfor %}
            </td>
        {% endfor %}
        </tr>
    {% endfor %}
    </table>
</ul>
{% else %}
<p>no sessions currently available</p>
{% endif %}